### ISSUE TITLE
Wifi crashes after control is connected

### ISSUE THREAD

**Issue by adrmartinez** [chrippa/ds4drv#50]
Hi 
anyone else is getting this issue? any idea?
Dist: Debian 3.2.63-2+deb7u1
hw: Intel Corporation Centrino Wireless-N 1030
driver: iwlwifi

**Comment by aus4000** [comment]
Are you using raw Bluetooth? Raw mode takes control over the card to connect to the controller first before anything else, and since your card is a Wifi+Bluetooth card it kicks your Wifi off as well. You might also run across an issue of raw kicking off all other BT devices too. It's normal, but an unintended side-effect of raw mode.

For more compatibility, try --hidraw. You won't be able to change your LED color (yet) and wireless polling to the controller will be slower, but it's more compatible if things are already connected.
